# 목차

1. 파이썬 - 타입, 라이브러리, 함수, 모듈, 클래스, 그래프 그리기

2. 파이토치 - 텐서, 역전파, 데이터 불러오기

3. 지도학습 - 집 값 예측, 이미지 분류, 주가 예측

4. 전이학습

5. 비지도 학습 - 오토인코더, 생성적 적대 신경망

6. 시각화 - 설명 가능한 AI, 차원 축소 기법

7. 성능 향상 - 과적합, 데이터 불균형 해결

#Module

코드를 구현할 때는 기능에 따라 파일을 별도로 만들어 전체적인 코드를 완성함.

별도의 파일을 생성하기 때문에 다른 업무에서 동일 작업이 필요할 때 파일만 불러와서 사용할 수 있다.

전역 변수, 함수 등을 포함한 별도의 파일

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [9]:
cd/content/drive/MyDrive/deeplearning/deeplearningbrov2/python

/content/drive/MyDrive/deeplearning/deeplearningbrov2/python


In [10]:
import numpy as np
import models # 모듈
# models.py를 불러옴
# models.py안에 있는 함수를 불러옴

In [11]:
data = np.random.randint(0,105, size=(10,5)) # 10행 5열 랜덤 데이터 뽑기

In [12]:
print(data)

[[63 40  8 94 86]
 [87 64 24 15 77]
 [53 67 66 44 56]
 [ 3 39 32 95 82]
 [ 7 96 69 11 81]
 [39 94  9 79 79]
 [25 78 83 95 31]
 [51 99 73 75 44]
 [78 92 76 33 50]
 [77 12 87 43 35]]


In [13]:
models.linear_regression(data)

Linear Regression


In [14]:
models.gaussian_mixture(data)

Gaussian Mixture


In [15]:
models.random_forest(data)

Random Forest
