Linear Regression : Linear regression is finding a straight line that best fits the training data. And it is W and b that define the best-fitting straight line. The goal of linear regression is to find the values ​​of W and b that define the best-fitting straight line.

Linear Regression Example

In [18]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1) # Set the random seed so that the random value is the same even if you rerun the Python code.

In [19]:
# Set dataset.
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[3],[5],[7]])
print(x_train)
print(x_train.shape,'\n')
print(y_train)
print(y_train.shape,'\n')

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1]) 

tensor([[3.],
        [5.],
        [7.]])
torch.Size([3, 1]) 



In [20]:
# Set weight, bais.
W = torch.zeros(1, requires_grad=True) # if "requires = True", it means that this variable is a variable whose value continues to change through learning.
b = torch.zeros(1, requires_grad=True)
print(W,'\n')
print(b)

tensor([0.], requires_grad=True) 

tensor([0.], requires_grad=True)


In [21]:
# Formulate a hypothesis.
hypo = x_train * W + b
print(hypo)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [22]:
# Prepare for learning by declaring the cost function.
cost = torch.mean((hypo - y_train)**2)
print(cost)

tensor(27.6667, grad_fn=<MeanBackward0>)


Linear Regression learning code implementation

In [37]:
# Gradient descent method implementation and learning progress Full code implementation

# Set dataset
x_train = torch.FloatTensor([1,2,3]).view(-1,1)
y_train = torch.FloatTensor([5,10,15]).view(-1,1)

# Model initialization
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# Set optimizer
optimizer = optim.SGD([W,b], lr=0.01)

# Repeat gradient descent as many times as desired
nb_epochs = 10000

During learning, the following process occurs every epoch.
- 1. Derive forecasts using current weights and biases
- 2. Derive loss value using predicted value and label
- 3. Differential initialization
- 4. Differential Calculation
- 5. W, b values update


In [38]:
# epoch : Iterative unit that learns the entire training dataset once
for epoch in range(nb_epochs+1):
  # hypothesis, cost function progress
  hypo = x_train * W + b
  cost = torch.mean((hypo - y_train)**2)

  # gradient descent progress
  optimizer.zero_grad() # In Pytorch, gradient values ​​are continuously added when doing backwards, so we should always start by setting the gradients to zero before doing backpropagation.
  cost.backward() # Finding the gradient by differentiating the cost function during the learning process is called a backward operation. cost.backward() means finding the slope from the cost function and is a backward operation.
  optimizer.step() # Update parameters using the gradient values ​​stored as the parameters of each layer. This command updates parameters and improves model performance.

  # Log output every 100 times
  if epoch % 100 == 0:
    print(f'Epoch {epoch:4d}/{nb_epochs} W:{W.item():.3f}, b:{b.item():.3f} Cost:{cost.item():.4f}')

Epoch    0/10000 W:0.467, b:0.200 Cost:116.6667
Epoch  100/10000 W:4.364, b:1.445 Cost:0.3011
Epoch  200/10000 W:4.500, b:1.136 Cost:0.1860
Epoch  300/10000 W:4.607, b:0.893 Cost:0.1150
Epoch  400/10000 W:4.691, b:0.702 Cost:0.0710
Epoch  500/10000 W:4.757, b:0.552 Cost:0.0439
Epoch  600/10000 W:4.809, b:0.434 Cost:0.0271
Epoch  700/10000 W:4.850, b:0.341 Cost:0.0168
Epoch  800/10000 W:4.882, b:0.268 Cost:0.0104
Epoch  900/10000 W:4.907, b:0.211 Cost:0.0064
Epoch 1000/10000 W:4.927, b:0.166 Cost:0.0040
Epoch 1100/10000 W:4.943, b:0.130 Cost:0.0024
Epoch 1200/10000 W:4.955, b:0.102 Cost:0.0015
Epoch 1300/10000 W:4.965, b:0.080 Cost:0.0009
Epoch 1400/10000 W:4.972, b:0.063 Cost:0.0006
Epoch 1500/10000 W:4.978, b:0.050 Cost:0.0004
Epoch 1600/10000 W:4.983, b:0.039 Cost:0.0002
Epoch 1700/10000 W:4.986, b:0.031 Cost:0.0001
Epoch 1800/10000 W:4.989, b:0.024 Cost:0.0001
Epoch 1900/10000 W:4.992, b:0.019 Cost:0.0001
Epoch 2000/10000 W:4.993, b:0.015 Cost:0.0000
Epoch 2100/10000 W:4.995, b:0.01

Linear Regression inference code implementation


In [40]:
# Inference about data whose outcome is unknown
test_data = torch.FloatTensor([[5]])
prediction = test_data * W + b
print(prediction)

tensor([[24.9999]], grad_fn=<AddBackward0>)
