#Tensor

- 행렬(matrix) : 2차원으로 구성된 데이터

- 텐서(Tensor) : 3차원으로 구성된 데이터

- 실제 프로그래밍을 할 때, 차원을 가진 1차원 이상의 데이터를 모두 텐서라고 표현함.

#Numpy

- 수치 계산, 통계, 신호 처리, 생물 정보학 등 상세한 숫자(큰 숫자 및 소수점 아래 표현력이 중요 숫자 등)을 다루는 분야를 위해 널리 쓰이는 파이썬 오픈 소스 라이브러리

- numpy 모듈을 import해서 사용할 수 있으며, numpy에서 글자 수를 줄이기 위해 np라는 별칭(alias)로 자주 쓰임.



In [1]:
import numpy as np # numpy 라이브러리 불러오기

In [4]:
a = np.array([1,2,3]) # rank = 1인 배열 생성
print(type(a)) # "<type 'numpy.ndarray'>" 출력
print()
print(a.shape) # "(3,)" 출력
print()
print(a[0], a[1], a[2]) # "1 2 3" 출력
a[0] = 5 # 요소를 변경
print()
print(a) # "5 2 3" 출력

<class 'numpy.ndarray'>

(3,)

1 2 3

[5 2 3]


In [6]:
b = np.array([[1,2,3] # rank = 2인 배열 생성
              ,[4,5,6]])
print(b.shape) # "(2,3)" 출력
print()
print(b[0,0], b[0,1], b[1,0]) # "1 2 4" 출력

(2, 3)

1 2 4


In [7]:
t = np.array([0.,1.,2.,3.,4.,5.,6.]) # rank = 1인 배열 생성

print('t[0] t[1] t[2] =',t[0], t[1], t[2]) # 인덱스를 통한 원소 접근
print('t[2:5] t[4:1] =', t[2:5], t[4:-1]) # [시작 번호 : 끝 번호]로  범위 지정을 통해 가져온다.
print('t[:2] t[3:] =', t[:2], t[3:]) # 시작 번호를 생략한 경우와 끝 번호를 생략한 경우

t[0] t[1] t[2] = 0.0 1.0 2.0
t[2:5] t[4:1] = [2. 3. 4.] [4. 5.]
t[:2] t[3:] = [0. 1.] [3. 4. 5. 6.]


In [8]:
x = np.array([1,2])
print(x.dtype) # "int64" 출력

int64


In [9]:
x = np.array([1.0, 2.0])
print(x.dtype) # "float64" 출력

float64


In [11]:
x = np.array([1,2], dtype = np.float64) # 특정 자료형 명시적으로 지정
print(x.dtype) # "float64" 출력

float64


In [12]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [13]:
# 요소별 합
print(x+y)
print()
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]

[[ 6.  8.]
 [10. 12.]]


In [14]:
# 요소별 차
print(x - y)
print()
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]

[[-4. -4.]
 [-4. -4.]]


In [15]:
# 요소별 곱
print(x*y)
print()
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]

[[ 5. 12.]
 [21. 32.]]


In [16]:
# 요소별 나눗셈
print(x/y)
print()
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [17]:
# 요소별 제곱근
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [18]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

In [19]:
# 벡터의 내적
print(v.dot(w))
print()
print(np.dot(v,w))

219

219


In [20]:
# 행렬과 벡터의 곱
print(x.dot(v))
print()
print(np.dot(x,v))

[29 67]

[29 67]


In [21]:
# 행렬곱
print(x.dot(y))
print()
print(np.dot(x,y))

[[19 22]
 [43 50]]

[[19 22]
 [43 50]]
