Torch : Torch is a tensor package with GPU support.

torch.autograd : automatic differentiation package

torch.nn : Neural network building and training package

torch.multiprocessing : Multiprocessing-related package, mainly used when calculations must be performed using multiple GPUs

torch.utils : Package that provides data-related classes and other utilities


In [2]:
import torch

t = torch.tensor([0,1,2,3,4,5,6])
print(t)
print(t.dim()) # rank
print(t.shape)
print(t.size()) # size() == shape
print(t.dtype) # data type...

tensor([0, 1, 2, 3, 4, 5, 6])
1
torch.Size([7])
torch.Size([7])
torch.int64


In [ ]:
print(t[0],t[1],t[-1])
print(t[2:5],t[4:-1]) # slicing
print(t[:2],t[3:]) # slicing

tensor(0) tensor(1) tensor(6)
tensor([2, 3, 4]) tensor([4, 5])
tensor([0, 1]) tensor([3, 4, 5, 6])


In [ ]:
# 2D tensor
t = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(t)
print(t.shape)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
torch.Size([4, 3])


In [ ]:
print(t[0,1])
print(t[0][1])

tensor(2.)
tensor(2.)


In [ ]:
print(t)
print(t[:,1]) # t[row,column] -> Returns the value with column index 1 when all rows are selected.
print(t[:,1].size())
print('\n')
print(t[:][1]) # Treated like a list
# You need to know exactly the difference between the two...

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


tensor([4., 5., 6.])


In [ ]:
print(t[:,:-1]) # In a situation where all rows are selected, :-1 in a column means slicing up to index -2.

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [ ]:
# Broadcasting -> Basically, the two tensors must have the same shape.
# The function of adjusting the tensor size and copying and filling in the values so that four arithmetic operations can be performed between tensors of different sizes is called broadcasting.
m1 = torch.FloatTensor([1])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[3., 3.]])


In [ ]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[4,5],[6,7]])

print(m1*m2) # broadcasting
print(m1.mul(m2)) # broadcasting

tensor([[ 4., 10.],
        [18., 28.]])
tensor([[ 4., 10.],
        [18., 28.]])


In [ ]:
print(m1.matmul(m2)) # matrix multiplication -> The commutative law does not apply and errors may occur if the sizes do not match.

tensor([[16., 19.],
        [36., 43.]])


In [3]:
t = torch.FloatTensor([[1,2,3],[8,9,10]])
print(t.mean())
print(t.mean().item()) # To convert a scalar tensor into a Python variable, you can use the .item() method.

tensor(5.5000)
5.5


In [6]:
print(t.mean(dim=0)) # dim = 0: Calculate the average by grouping columns together.
print(t.mean(dim=0).shape)

tensor([4.5000, 5.5000, 6.5000])
torch.Size([3])


In [7]:
print(t.mean(dim=1)) # t.mean(dim=1) == t.mean(dim=-1) : The average is calculated by grouping rows together.
print(t.mean(dim=1).shape) # Because the dimension disappears completely, it is output in the form of shape [2].

tensor([2., 9.])
torch.Size([2])


In [15]:
t = torch.FloatTensor([[0,2,4],[6,8,10]])

print(t.sum(),'\n')
print(t.sum(dim=0))
print(t.sum(dim=0).shape,'\n')
print(t.sum(dim=1))
print(t.sum(dim=1).shape,'\n')
print(t.sum(dim=-1))
print(t.sum(dim=-1).shape,'\n')

tensor(30.) 

tensor([ 6., 10., 14.])
torch.Size([3]) 

tensor([ 6., 24.])
torch.Size([2]) 

tensor([ 6., 24.])
torch.Size([2]) 



In [20]:
print(t,'\n')
print(t.max(),'\n')
# Return maximum value and index information
print(t.max(dim=0),'\n')
print(t.max(dim=1),'\n')
print("Values :",t.max(dim=1)[0])
print("idex location information :",t.max(dim=1)[1])

tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]]) 

tensor(10.) 

torch.return_types.max(
values=tensor([ 6.,  8., 10.]),
indices=tensor([1, 1, 1])) 

torch.return_types.max(
values=tensor([ 4., 10.]),
indices=tensor([2, 2])) 

Values : tensor([ 4., 10.])
idex location information : tensor([2, 2])


In [21]:
t = torch.FloatTensor([[[1,3,5],[7,9,11]],[[0,2,4],[6,8,10]]])
print(t)
print(t.shape)

tensor([[[ 1.,  3.,  5.],
         [ 7.,  9., 11.]],

        [[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]])
torch.Size([2, 2, 3])


In [24]:
# view method : The shape can be changed while maintaining the elements of the tensor.
print(t.view(2,3,2),'\n')
# An argument with a value of -1 can be used only once within the view method, and a dimension with -1 entered is interpreted as PyTorch automatically adjusting the size.
print(t.view(-1,4))

tensor([[[ 1.,  3.],
         [ 5.,  7.],
         [ 9., 11.]],

        [[ 0.,  2.],
         [ 4.,  6.],
         [ 8., 10.]]]) 

tensor([[ 1.,  3.,  5.,  7.],
        [ 9., 11.,  0.,  2.],
        [ 4.,  6.,  8., 10.]])
