Manipulating tensors in PyTorch

In [1]:
import torch

In [5]:
# squeeze() method: A function that removes all dimensions of size 1 by squeezing the tensor.
t = torch.FloatTensor([[0],[2],[4],[6]])
print(t)
print(t.shape,'\n')
print(t.squeeze())
print(t.squeeze().shape,'\n')

tensor([[0.],
        [2.],
        [4.],
        [6.]])
torch.Size([4, 1]) 

tensor([0., 2., 4., 6.])
torch.Size([4]) 



In [9]:
# unsqueeze() method: Adds a dimension of size 1 to the input index.
t = torch.FloatTensor([1,2,4,8,16])
print(t)
print(t.shape,'\n')
print(t.unsqueeze(0)) # Since the index starts from 0, 0 refers to the first dimension.
print(t.unsqueeze(0).shape,'\n')
print(t.unsqueeze(1)) # Since the index starts from 1, 1 refers to the second dimension.
print(t.unsqueeze(1).shape,'\n')

tensor([ 1.,  2.,  4.,  8., 16.])
torch.Size([5]) 

tensor([[ 1.,  2.,  4.,  8., 16.]])
torch.Size([1, 5]) 

tensor([[ 1.],
        [ 2.],
        [ 4.],
        [ 8.],
        [16.]])
torch.Size([5, 1]) 



In [11]:
# Type casting : The type of a tensor can be changed through methods corresponding to each tensor type name, such as long(), float(), and double().
t = torch.DoubleTensor([2,4,8,16,32])
print(t)
print(t.long())
print(t.float())

tensor([ 2.,  4.,  8., 16., 32.], dtype=torch.float64)
tensor([ 2,  4,  8, 16, 32])
tensor([ 2.,  4.,  8., 16., 32.])


In [15]:
# Concatenate -> torch.cat(): This function can connect tensors. At this time, which index dimension to connect must be entered through the dim parameter.
x = torch.FloatTensor([[0,2],
                       [4,6]]) # 2 x 2
y = torch.FloatTensor([[1,3],
                       [5,7]]) # 2 x 2

print(torch.cat([x,y],dim=0),'\n')
print(torch.cat([x,y],dim=1))

tensor([[0., 2.],
        [4., 6.],
        [1., 3.],
        [5., 7.]]) 

tensor([[0., 2., 1., 3.],
        [4., 6., 5., 7.]])


In [20]:
x = torch.FloatTensor([[0,2],
                       [4,6],
                       [8,10]]) # 3 x 2
y = torch.FloatTensor([[1,3,5],
                       [7,9,11]]) # 2 x 3

y = y.view(3,2)
print(y,'\n')
print(torch.cat([x,y],dim=0),'\n')
print(torch.cat([x,y],dim=1))

tensor([[ 1.,  3.],
        [ 5.,  7.],
        [ 9., 11.]]) 

tensor([[ 0.,  2.],
        [ 4.,  6.],
        [ 8., 10.],
        [ 1.,  3.],
        [ 5.,  7.],
        [ 9., 11.]]) 

tensor([[ 0.,  2.,  1.,  3.],
        [ 4.,  6.,  5.,  7.],
        [ 8., 10.,  9., 11.]])


In [22]:
# ones_like(), zeros_like() : These function can create a tensor filled with 1 or a tensor filled with 0 with the same shape as the input tensor.
t = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(t,'\n')
print(torch.ones_like(t),'\n')
print(torch.zeros_like(t))

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]]) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [24]:
# ones(), zero() : By entering shape information as if entering the view() method, you can create a tensor filled with 1 or 0 with the corresponding shape.
print(torch.ones(5,4),'\n') # Creates a tensor filled with 1 or 0 by specifying the shape.
print(torch.zeros(1,1))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

tensor([[0.]])
