#List Comprehension
- 리스트 내에 for문을 포함하는 형식의 문법
- [표현식 for 항목 in 반복가능객체 if 조건문]

In [ ]:
List = [i for i in range(10) if i % 2 == 0]
print(List)

[0, 2, 4, 6, 8]


#Overriding
- 부모 클래스에 있는 메서드를 다시 정의하는 것.

#Overloading
- 같은 이름이지만 매개변수 타입이나 갯수가 다른 함수들을 정의하는 것.

#Encapsulation
- 클래스 외부에서는 허용된 메서드 및 데이터에만 접근할 수 있도록 Attribute 및 method에 대해 접근 권한을 부여하는 것을 의미함.

#if __name__ == "__main__":
- 모듈 파일 내에서 테스트 등을 목적으로 코드를 작성하고, 해당 모듈을 불러올 때는 실행되지 않도록 if __name__ == "__main__": 문구를 활용할 수 있음.

- 파이썬에서는 현재 포함된 모든 모듈들의 __name__속성을 관리하는데, 가장 처음 실행된 모듈은 __main__이라는 값을 갖고, 나머지는 모듈명에 해당하는 __name__을 갖는다.

- 즉, .py를 직접 실행할 때만 print 구문들이 작동하고 import할 때는 작동하지 않음.

#패키지
- 패키지는 파이썬 모듈들이 계층적으로 모인 모듈들의 묶음을 의미함.

- 파일 시스템 상의 경로를 표현할 때 / 연산자를 사용해 계층 관계를 표현하는 것과 유사하게 파이썬 패키지는 . 연산자로서 계층적 구조를 표현함

- 파이썬 라이브러리는 파이썬을 설치할 때 같이 설치되는 모듈들의 집합으로써 다양한 상황에 쓰일 수 있는 유용한 모듈들이 다수 포함되어 있음.

- ex) import game.sound.echo
      game.sound.echo_test()


#PyTorch란?
- 딥러닝 프레임워크의 일종
- 목적에 필요한 것을 고민할 필요 없이 이용할 수 있도록 일괄로 가져다 쓰도록 만들어 놓은 '구조화된 틀'이다.
- GPU에서 텐서를 조작하고 신경망을 구축하여 딥러닝 관련 작업을 수행하기에 용이함.
- 딥러닝 관련 연산에서는 행렬 연산(행렬곱)이 많이 요구되는데, 행렬 연산은 병렬화가 가능하므로 코어 수가 많을수록 유리함.

#PyTorch 아키텍처
- torch: GPU를 지원하는 텐서 패키지
- torch.autograd: 자동 미분 패키지.
- torch.nn: 신경망 구축 및 훈련 패키지. 미리 구현된 클래스들을 이용해 원하는 모델
구현 가능
- torch.multiprocessing: 멀티프로세싱 관련 패키지. 여러 개의 GPU를 사용해서 연산해야 하는 경우 주로 사용하게 됨.
- torch.utils: 데이터 관련 클래스 및 기타 유틸리티를 제공하는 패키지


In [2]:
import torch

In [2]:
t = torch.tensor([0,1,2,3,4,5,6]) # 텐서 생성
print(t) # 텐서 출력

tensor([0, 1, 2, 3, 4, 5, 6])


In [3]:
print(t.dim()) # rank(차원)

1


In [4]:
print(t.shape) # 텐서 shape

torch.Size([7])


In [5]:
print(t.size()) # 텐서 shape

torch.Size([7])


In [6]:
print(t.dtype) # data type

torch.int64


#PyTorch에서 텐서 다루기
- torch.FloatTensor: 32비트 부동 소수점 실수형
- torch.DoubleTensor: 64비트 부동 소수점 실수형
- torch.LongTensor: 64비트 정수형
- .dim(): 해당 텐서가 몇 차원인지를 반환
- .shape: 해당 텐서의 모양에 관한 attribute
- .size(): shape attribute 반환
- .dtype: 해당 텐서의 자료형에 관한 attribute

In [7]:
# 1D Tensor 다루기
t = torch.FloatTensor([0,1,2,3,4,5,6])
print(t) # 텐서 출력

tensor([0., 1., 2., 3., 4., 5., 6.])


In [8]:
print(t.shape) # 텐서 shape

torch.Size([7])


In [9]:
print(t.dtype) # data type

torch.float32


In [10]:
print(t[0], t[1], t[-1]) # 인덱스로 접근

tensor(0.) tensor(1.) tensor(6.)


In [11]:
print(t[2:5], t[4:-1]) # 슬라이싱

tensor([2., 3., 4.]) tensor([4., 5.])


In [12]:
print(t[:2],t[3:]) # 슬라이싱

tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [15]:
# 2D 텐서 다루기
t = torch.FloatTensor([[1.,2.,3.],
                       [4.,5.,6.],
                       [7.,8.,9.],
                       [10.,11.,12.]])
print(t) # 텐서 출력

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [16]:
print(t.shape) # 텐서 shape 4행 3열

torch.Size([4, 3])


In [17]:
print(t[0,1])

tensor(2.)


In [18]:
print(t[0][1])

tensor(2.)


In [19]:
print(t[:,1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원은 첫째 것만 가져온다.

tensor([ 2.,  5.,  8., 11.])


In [20]:
print(t[:,1].size()) # 2열의 shape(크기) -> 전체 행 중에 2열 슬라이싱

torch.Size([4])


In [21]:
print(t[:][1]) # [:,1]과 다르게 모든 구간을 슬라이싱한 상태에서 인덱스 1의 값을 가져옴

tensor([4., 5., 6.])


In [22]:
print(t[:, :-1]) # 전체 행 중에서 2열까지 슬라이싱

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


- Broadcasting
  - 텐서끼리의 사칙연산은 기본적으로 두 텐서의 shape가 같아야 함.
  - 크기가 다른 텐서끼리의 사칙연산을 수행할 수 있도록 텐서 크기를 맞추고 값을 복사해서 채워넣는 기능
  - 스칼라의 연산뿐 아니라 벡터끼리의 연산에서도 브로드 캐스팅 가능
  - 브로드 캐스팅은 잘 파악하고 이용하면 편리하지만, 의도하지 않은 브로드캐스팅으로 인해 잘못된 연산을 수행하는 경우를 조심해야 함.
  - 스칼라 데이터에 대해서만 브로드 캐스팅 기능 활용 추천

- Element-wise multiplication
  - 텐서 사이에 *를 사용해서 연산을 수행하거나, mul 메서드를 통해 연산을 수행하면, element-wise multiplication이 수행됨.

In [24]:
# Broadcasting
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
'''
[[1,2],  +  [[3,3],
 [1,2]]      [4,4]]
'''
print(m1)
print()
print(m2)
print()
print(m1 + m2)

tensor([[1., 2.]])

tensor([[3.],
        [4.]])

tensor([[4., 5.],
        [5., 6.]])


In [25]:
m1 = torch.FloatTensor([[1,2,3]])
m2 = torch.FloatTensor([[3],[4],[5]])
print(m1+m2)

tensor([[4., 5., 6.],
        [5., 6., 7.],
        [6., 7., 8.]])


In [26]:
# Element-wise multiplication
m1 = torch.FloatTensor([[1,2]
                        ,[3,4]])
m2 = torch.FloatTensor([[4,5]
                        ,[6,7]])
print(m1 * m2)
print()
print(m1.mul(m2))

tensor([[ 4., 10.],
        [18., 28.]])

tensor([[ 4., 10.],
        [18., 28.]])


In [27]:
# Matrix multiplication
# 행렬곱은 교환법칙이 적용되지 않으며, 크기가 맞지 않으면 에러가 날 수 있음에 유의해야 함.
m1 = torch.FloatTensor([[1,2]
                        ,[3,4]])
m2 = torch.FloatTensor([[1]
                        ,[2]])

print('Shape of Matrix1:', m1.shape)
print('Shape of Matrix2:', m2.shape)
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix1: torch.Size([2, 2])
Shape of Matrix2: torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [29]:
# 평균
t = torch.FloatTensor([[1,2,3]
                       ,[4,5,6]])
print(t.mean())

tensor(3.5000)


In [31]:
print(t.mean().item()) # .item() 메서드를 통해 값만 뽑아낼 수 있다.

3.5


In [32]:
print(type(t.mean().item()))

<class 'float'>


In [33]:
# 평균
# .mean() 메서드에서는 dim을 매개변수에 넣어서 특정 차원에 대한 평균을 구할 수 있다.
print(t.mean(dim=0)) # 행끼리 합하여 이것을 평균으로 만듦

tensor([2.5000, 3.5000, 4.5000])


In [34]:
print(t.mean(dim=1)) # 열끼리 합하여 이것을 평균으로 만듦

tensor([2., 5.])


In [35]:
print(t.sum()) # 숫자 전체 합

tensor(21.)


In [36]:
print(t.sum(dim=0)) # 행끼리 합

tensor([5., 7., 9.])


In [37]:
print(t.sum(dim=1)) # 열끼리 합

tensor([ 6., 15.])


In [38]:
print(t.sum(dim=-1)) # 열끼리 합

tensor([ 6., 15.])


In [39]:
print(t.max()) # 행렬에서의 요소값들 중 최대값

tensor(6.)


In [42]:
print(t.max(dim=0)) # 행렬 중에서 제일 높은 요소값의 행을 출력한다.

torch.return_types.max(
values=tensor([4., 5., 6.]),
indices=tensor([1, 1, 1]))


In [43]:
print(t.max(dim=1)) # 행렬 중에서 제일 높은 요소값의 열을 출력한다.
# indices: index의 복수형

torch.return_types.max(
values=tensor([3., 6.]),
indices=tensor([2, 2]))


In [48]:
t = torch.FloatTensor([[[0,1,2]
                        ,[3,4,5]]
                       ,[[6,7,8]
                         ,[9,10,11]]])
print(t)
print()
print(t.shape) # batch size x 행 x 열

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])

torch.Size([2, 2, 3])


In [46]:
# view: 텐서 shape 변경하기
print(t.view(4,3))
print()
print(t.view(2,1,6))

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.]],

        [[ 6.,  7.,  8.,  9., 10., 11.]]])


In [47]:
# view안에서 -1의 값을 넣으면, -1이 입력된 차원은 PyTorch에서 알아서 크기를 맞추라는 것으로 해석된다
# 이 -1은 view 메서드 내에서 단 한번 사용할 수 있다.
print(t.view(-1,3))

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])


In [50]:
print(t.view(-1,3).shape)

torch.Size([4, 3])


In [51]:
# squeeze() 메서드: 텐서를 눌러서 크기가 1인 차원은 모두 제거하는 기능
ft = torch.FloatTensor([[0]
                        ,[1]
                        ,[2]])
print(ft)

tensor([[0.],
        [1.],
        [2.]])


In [52]:
print(ft.shape)

torch.Size([3, 1])


In [53]:
print(ft.squeeze())

tensor([0., 1., 2.])


In [54]:
print(ft.squeeze().shape)

torch.Size([3])


In [3]:
# unsqueeze() 메서드: 입력받은 인덱스에 크기가 1인 차원을 추가함.
ft = torch.Tensor([0,1,2])
print(ft)

tensor([0., 1., 2.])


In [4]:
print(ft.shape)

torch.Size([3])


In [6]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미함.

tensor([[0., 1., 2.]])


In [7]:
print(ft.unsqueeze(0).shape) # 첫번째 부분에서 1차원 추가됨

torch.Size([1, 3])


#view, squeeze, unsqueeze
- view(), squeeze(), unsqueeze() 메서드 모두 텐서의 요소들을 그대로 유지하면서 shape을 바꾸는 기능을 함.

- view()를 통해서 squeeze(), unsqueeze()의 기능을 대체할 수 있으나, 크기가 1인 차원을 없애거나 추가할 일이 자주 있기 때문에 따로 메서드가 존재함.

#Type casting
- long(), float(), double() 등 각 텐서 타입 이름에 해당하는 메서드를 통해 텐서의 타입을 변경할 수 있음.




In [8]:
# Type casting
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [9]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [10]:
print(lt.double())

tensor([1., 2., 3., 4.], dtype=torch.float64)


In [13]:
print(lt.float().dtype)
print(lt.double().dtype)

torch.float32
torch.float64


In [14]:
# Concatenate
# torch.cat(): 함수를 통해서 텐서끼리 연결할 수 있음.
# 어떤 인덱스의 차원을 연결할 것인지를 dim 매개변수를 통해서 입력해주어야 함.

x = torch.FloatTensor([[1,2]
                       ,[3,4]])
y = torch.FloatTensor([[5,6]
                       ,[7,8]])

print(torch.cat([x,y], dim=0)) # 행이 늘어남

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [15]:
print(torch.cat([x,y],dim=1)) # 열이 늘어남

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [16]:
# ones_like, zeros_like
# torch.ones_like(), torch.zeros_like() 함수를 통해서 입력받는 텐서의 shape과 똑같은 shape을 가지면서 1로 채워진 텐서 혹은 0으로 채워진 텐서를 생성 가능

x = torch.FloatTensor([[0,1,2]
                       ,[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [17]:
print(torch.ones_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채운 텐서 출력

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [18]:
print(torch.zeros_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 0으로 채운 텐서 출력

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [19]:
# ones, zeros
# torch.ones(), torch.zeros() 함수를 이용하면 view() 메서드에 입력하듯 shape 정보를 입력해서 해당 shape을 가지면서 1로 채워졌거나 0으로 채워진 텐서를 생성할 수 있음.

print(torch.ones(2,3)) # shape를 지정하여 1로 채운 텐서 생성

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [20]:
print(torch.zeros(3,2)) # shape를 지정하여 0으로 채운 텐서 생성

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
