# 목차

1. 파이썬 - 타입, 라이브러리, 함수, 모듈, 클래스, 그래프 그리기

2. 파이토치 - 텐서, 역전파, 데이터 불러오기

3. 지도학습 - 집 값 예측, 이미지 분류, 주가 예측

4. 전이학습

5. 비지도 학습 - 오토인코더, 생성적 적대 신경망

6. 시각화 - 설명 가능한 AI, 차원 축소 기법

7. 성능 향상 - 과적합, 데이터 불균형 해결

#1. Numpy 배열

In [1]:
import numpy # 라이브러리 불러오기

In [2]:
arr = numpy.array([1,2,3,4])
print(arr, type(arr))

[1 2 3 4] <class 'numpy.ndarray'>


#2. 라이브러리

import를 통해 미리 만들어 놓은 함수와 클래스를 쉽게 사용할 수 있다.

In [3]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4])
print(arr, type(arr))

[1 2 3 4] <class 'numpy.ndarray'>


In [6]:
# numpy 내 특정 함수만 불러오기
from numpy import array, ones, zeros

In [8]:
a = array([1,2,3,4])
b = ones(5)
c = zeros((5,3))

In [12]:
print(a)
print()
print(b)
print()
print(c)

[1 2 3 4]

[1. 1. 1. 1. 1.]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
